Add cava module

diff --git a/lib/dzen2-status-bar/functions b/lib/dzen2-status-bar/functions
--- a/lib/dzen2-status-bar/functions
+++ b/lib/dzen2-status-bar/functions
@@ -1,5 +1,15 @@
 #!/usr/bin/env bash
 
+CFG_HEIGHT="${CFG_HEIGHT:-24}"
+
+if [ -z "${CFG_REPLACE_MAP+x}" ]; then
+  declare -A CFG_REPLACE_MAP=()
+fi
+
+if [ -z "${CFG_DEFAULT_STACK_COLORS+x}" ]; then
+  CFG_DEFAULT_STACK_COLORS=('#ff8b92' '#c3e88d' '#e1acff' '#ffe585')
+fi
+
 check_dependencies() {
     local missing_dependencies=()
 
@@ -12,7 +22,7 @@ check_dependencies() {
 
     # If there are missing dependencies, print them and exit
     if [ ${#missing_dependencies[@]} -ne 0 ]; then
-        echo >&2 "Missing dependencies: ${missing_dependencies[@]}"
+        echo >&2 "Missing executables: ${missing_dependencies[@]}"
         exit 1
     fi
 }
@@ -57,8 +67,6 @@ extract_param_value() {
 
     echo "$param_value"
 }
-
-DEFAULT_STACK_COLORS=("#ff8b92" "#c3e88d" "#e1acff" "#ffe585")
 
 #######################################################
 # Dzen2 utils
@@ -166,7 +174,7 @@ dzen2_draw_h_stacked_bars() {
     local max_value=100
     local stacks=1
     local values=()
-    local fg_colors=("#ff8b92" "#c3e88d" "#e1acff" "#ffe585")
+    local fg_colors=("${CFG_DEFAULT_STACK_COLORS[@]}")
     local bar_padding=1
     local stack_padding=1
     local bg="#333"
